### PR TITLE
Feature health check indicator for Spring boot actuator

### PR DESCRIPTION
**Pull request by ganchix**
Added a health check indicator for Spring boot actuator.

Indicates the following metrics:

- netVersion
- clientVersion
- blockNumber
- protocolVersion

### CODE REVIEW

**Comment by conor10** [comment]
Cool - are you able to add some unit tests for this please?

**Comment by ganchix** [comment]
No problem, I will do this weekend. Thanks

**Comment by ganchix** [comment]
Done! Thanks for your review.

**Comment by conor10** [comment]
A very useful change 👍 

I've cleaned up some of the code - removed unused imports and exception checks - please keep an eye on these for future reference.

**Pull request merged**
