### PR TITLE
include networkId in the properties

### PR DESCRIPTION
**Pull request by eepstein**

### CODE REVIEW

**Comment by conor10** [comment]
It would be nice to wire this property into the RawTransactionManager automatically on application startup if it's present.

**Comment by eepstein** [comment]
point me to it, along with pseudo code (or details in other form) and I'm happy to add it in.

**Comment by eepstein** [comment]
I've added you as a contributor to the fork in case it's a trivial change and that's the easiest way to include it in this pull req.

**Comment by conor10** [comment]
Integration with RawTransactionManager is non-trivial change (it won't work out the box with smart contract wrappers etc), so merging this. Thanks for submitting.

**Pull request merged**
